services:
  - type: worker
    name: obeida-online-bot
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TZ
        value: Asia/Baghdad
